### ISSUE TITLE
Compare dois before pinging the API

### ISSUE THREAD

**Issue by SamGuay** [koudyk/cleanBibImpact#24]
Right now, every time the script runs, it goes through the list and makes a new database every time, which triggers the API and take a long time to process.

We could simply make sure to compare the dois from the _old_ database to the ones from the `get_doi()`, and update it with only the new dois.

**Comment by SamGuay** [comment]
Pinging @FrancoisPgm here just in case you hadn't seen this issue. This would also fasten the whole workflow after it's run for the first time.

**Comment by FrancoisPgm** [comment]
Adressed by the commit d8b48c14723d197e2d4185265f78372d8e8e249e, now it looks for `../../data/citing_papers.csv` and only process citing DOIs that are not already in the file. If it doesn't find the csv file, it starts from scratch. But I also added an update of the paths so that they are relative to the working dir from which the script is run, so that you don't have to re-start from scratch if you forget to go to `src/data`.
